/* eslint-disable */

// @ts-nocheck

// This file is generated by TanStack Router. It was refreshed manually here
// because the local install was unavailable during the CMS integration.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminArtworksRouteImport } from './routes/admin.artworks'
import { Route as AdminArtworkNewRouteImport } from './routes/admin.artworks.new'
import { Route as AdminArtworkEditRouteImport } from './routes/admin.artworks.$artworkId'
import { Route as AdminSeriesRouteImport } from './routes/admin.series'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as ArtworkSlugRouteImport } from './routes/artwork.$slug'
import { Route as ApiArtworksRouteImport } from './routes/api.artworks'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiNewsletterRouteImport } from './routes/api.newsletter'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAdminArtworksRouteImport } from './routes/api.admin.artworks'
import { Route as ApiAdminArtworkRouteImport } from './routes/api.admin.artworks.$artworkId'
import { Route as ApiAdminArtworkReorderRouteImport } from './routes/api.admin.artworks.reorder'
import { Route as ApiAdminSeriesRouteImport } from './routes/api.admin.series'
import { Route as ApiAdminInquiriesRouteImport } from './routes/api.admin.inquiries'
import { Route as ApiAdminSettingsRouteImport } from './routes/api.admin.settings'
import { Route as RobotsRouteImport } from './routes/robots[.]txt'
import { Route as SitemapRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

const AdminArtworksRoute = AdminArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => AdminRoute,
} as any)

const AdminArtworkNewRoute = AdminArtworkNewRouteImport.update({
  id: '/artworks/new',
  path: '/artworks/new',
  getParentRoute: () => AdminRoute,
} as any)

const AdminArtworkEditRoute = AdminArtworkEditRouteImport.update({
  id: '/artworks/$artworkId',
  path: '/artworks/$artworkId',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSeriesRoute = AdminSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AdminRoute,
} as any)

const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

const ArtworkSlugRoute = ArtworkSlugRouteImport.update({
  id: '/artwork/$slug',
  path: '/artwork/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiArtworksRoute = ApiArtworksRouteImport.update({ id: '/api/artworks', path: '/api/artworks', getParentRoute: () => rootRouteImport } as any)
const ApiContactRoute = ApiContactRouteImport.update({ id: '/api/contact', path: '/api/contact', getParentRoute: () => rootRouteImport } as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({ id: '/api/newsletter', path: '/api/newsletter', getParentRoute: () => rootRouteImport } as any)
const ApiUploadRoute = ApiUploadRouteImport.update({ id: '/api/upload', path: '/api/upload', getParentRoute: () => rootRouteImport } as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({ id: '/api/auth/login', path: '/api/auth/login', getParentRoute: () => rootRouteImport } as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({ id: '/api/auth/logout', path: '/api/auth/logout', getParentRoute: () => rootRouteImport } as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({ id: '/api/auth/me', path: '/api/auth/me', getParentRoute: () => rootRouteImport } as any)
const ApiAdminArtworksRoute = ApiAdminArtworksRouteImport.update({ id: '/api/admin/artworks', path: '/api/admin/artworks', getParentRoute: () => rootRouteImport } as any)
const ApiAdminArtworkRoute = ApiAdminArtworkRouteImport.update({ id: '/api/admin/artworks/$artworkId', path: '/api/admin/artworks/$artworkId', getParentRoute: () => rootRouteImport } as any)
const ApiAdminArtworkReorderRoute = ApiAdminArtworkReorderRouteImport.update({ id: '/api/admin/artworks/reorder', path: '/api/admin/artworks/reorder', getParentRoute: () => rootRouteImport } as any)
const ApiAdminSeriesRoute = ApiAdminSeriesRouteImport.update({ id: '/api/admin/series', path: '/api/admin/series', getParentRoute: () => rootRouteImport } as any)
const ApiAdminInquiriesRoute = ApiAdminInquiriesRouteImport.update({ id: '/api/admin/inquiries', path: '/api/admin/inquiries', getParentRoute: () => rootRouteImport } as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({ id: '/api/admin/settings', path: '/api/admin/settings', getParentRoute: () => rootRouteImport } as any)
const RobotsRoute = RobotsRouteImport.update({ id: '/robots.txt', path: '/robots.txt', getParentRoute: () => rootRouteImport } as any)
const SitemapRoute = SitemapRouteImport.update({ id: '/sitemap.xml', path: '/sitemap.xml', getParentRoute: () => rootRouteImport } as any)

const AdminRouteChildren = {
  AdminIndexRoute,
  AdminLoginRoute,
  AdminArtworksRoute,
  AdminArtworkNewRoute,
  AdminArtworkEditRoute,
  AdminSeriesRoute,
  AdminInquiriesRoute,
  AdminSettingsRoute,
}

const rootRouteChildren = {
  IndexRoute,
  AdminRoute: AdminRoute._addFileChildren(AdminRouteChildren),
  ArtworkSlugRoute,
  ApiArtworksRoute,
  ApiContactRoute,
  ApiNewsletterRoute,
  ApiUploadRoute,
  ApiAuthLoginRoute,
  ApiAuthLogoutRoute,
  ApiAuthMeRoute,
  ApiAdminArtworksRoute,
  ApiAdminArtworkRoute,
  ApiAdminArtworkReorderRoute,
  ApiAdminSeriesRoute,
  ApiAdminInquiriesRoute,
  ApiAdminSettingsRoute,
  RobotsRoute,
  SitemapRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
