/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ArtworkSlugRouteImport } from './routes/artwork.$slug'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiNewsletterRouteImport } from './routes/api.newsletter'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiArtworksRouteImport } from './routes/api.artworks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeriesRouteImport } from './routes/admin.series'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminArtworksRouteImport } from './routes/admin.artworks'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAdminSettingsRouteImport } from './routes/api.admin.settings'
import { Route as ApiAdminSeriesRouteImport } from './routes/api.admin.series'
import { Route as ApiAdminInquiriesRouteImport } from './routes/api.admin.inquiries'
import { Route as ApiAdminArtworksRouteImport } from './routes/api.admin.artworks'
import { Route as AdminArtworksNewRouteImport } from './routes/admin.artworks.new'
import { Route as AdminArtworksArtworkIdRouteImport } from './routes/admin.artworks.$artworkId'
import { Route as ApiAdminArtworksReorderRouteImport } from './routes/api.admin.artworks.reorder'
import { Route as ApiAdminArtworksArtworkIdRouteImport } from './routes/api.admin.artworks.$artworkId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ArtworkSlugRoute = ArtworkSlugRouteImport.update({
  id: '/artwork/$slug',
  path: '/artwork/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtworksRoute = ApiArtworksRouteImport.update({
  id: '/api/artworks',
  path: '/api/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeriesRoute = AdminSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtworksRoute = AdminArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeriesRoute = ApiAdminSeriesRouteImport.update({
  id: '/api/admin/series',
  path: '/api/admin/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInquiriesRoute = ApiAdminInquiriesRouteImport.update({
  id: '/api/admin/inquiries',
  path: '/api/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminArtworksRoute = ApiAdminArtworksRouteImport.update({
  id: '/api/admin/artworks',
  path: '/api/admin/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArtworksNewRoute = AdminArtworksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArtworksRoute,
} as any)
const AdminArtworksArtworkIdRoute = AdminArtworksArtworkIdRouteImport.update({
  id: '/$artworkId',
  path: '/$artworkId',
  getParentRoute: () => AdminArtworksRoute,
} as any)
const ApiAdminArtworksReorderRoute = ApiAdminArtworksReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => ApiAdminArtworksRoute,
} as any)
const ApiAdminArtworksArtworkIdRoute =
  ApiAdminArtworksArtworkIdRouteImport.update({
    id: '/$artworkId',
    path: '/$artworkId',
    getParentRoute: () => ApiAdminArtworksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/artworks': typeof AdminArtworksRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/series': typeof AdminSeriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/artworks': typeof ApiArtworksRoute
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/upload': typeof ApiUploadRoute
  '/artwork/$slug': typeof ArtworkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/artworks/$artworkId': typeof AdminArtworksArtworkIdRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/api/admin/artworks': typeof ApiAdminArtworksRouteWithChildren
  '/api/admin/inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin/series': typeof ApiAdminSeriesRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/admin/artworks/$artworkId': typeof ApiAdminArtworksArtworkIdRoute
  '/api/admin/artworks/reorder': typeof ApiAdminArtworksReorderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/artworks': typeof AdminArtworksRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/series': typeof AdminSeriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/artworks': typeof ApiArtworksRoute
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/upload': typeof ApiUploadRoute
  '/artwork/$slug': typeof ArtworkSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/artworks/$artworkId': typeof AdminArtworksArtworkIdRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/api/admin/artworks': typeof ApiAdminArtworksRouteWithChildren
  '/api/admin/inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin/series': typeof ApiAdminSeriesRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/admin/artworks/$artworkId': typeof ApiAdminArtworksArtworkIdRoute
  '/api/admin/artworks/reorder': typeof ApiAdminArtworksReorderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/artworks': typeof AdminArtworksRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/series': typeof AdminSeriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/artworks': typeof ApiArtworksRoute
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/upload': typeof ApiUploadRoute
  '/artwork/$slug': typeof ArtworkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/artworks/$artworkId': typeof AdminArtworksArtworkIdRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/api/admin/artworks': typeof ApiAdminArtworksRouteWithChildren
  '/api/admin/inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin/series': typeof ApiAdminSeriesRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/admin/artworks/$artworkId': typeof ApiAdminArtworksArtworkIdRoute
  '/api/admin/artworks/reorder': typeof ApiAdminArtworksReorderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/artworks'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/series'
    | '/admin/settings'
    | '/api/artworks'
    | '/api/contact'
    | '/api/newsletter'
    | '/api/upload'
    | '/artwork/$slug'
    | '/admin/'
    | '/admin/artworks/$artworkId'
    | '/admin/artworks/new'
    | '/api/admin/artworks'
    | '/api/admin/inquiries'
    | '/api/admin/series'
    | '/api/admin/settings'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/admin/artworks/$artworkId'
    | '/api/admin/artworks/reorder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/artworks'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/series'
    | '/admin/settings'
    | '/api/artworks'
    | '/api/contact'
    | '/api/newsletter'
    | '/api/upload'
    | '/artwork/$slug'
    | '/admin'
    | '/admin/artworks/$artworkId'
    | '/admin/artworks/new'
    | '/api/admin/artworks'
    | '/api/admin/inquiries'
    | '/api/admin/series'
    | '/api/admin/settings'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/admin/artworks/$artworkId'
    | '/api/admin/artworks/reorder'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/artworks'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/series'
    | '/admin/settings'
    | '/api/artworks'
    | '/api/contact'
    | '/api/newsletter'
    | '/api/upload'
    | '/artwork/$slug'
    | '/admin/'
    | '/admin/artworks/$artworkId'
    | '/admin/artworks/new'
    | '/api/admin/artworks'
    | '/api/admin/inquiries'
    | '/api/admin/series'
    | '/api/admin/settings'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/admin/artworks/$artworkId'
    | '/api/admin/artworks/reorder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiArtworksRoute: typeof ApiArtworksRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ArtworkSlugRoute: typeof ArtworkSlugRoute
  ApiAdminArtworksRoute: typeof ApiAdminArtworksRouteWithChildren
  ApiAdminInquiriesRoute: typeof ApiAdminInquiriesRoute
  ApiAdminSeriesRoute: typeof ApiAdminSeriesRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/artwork/$slug': {
      id: '/artwork/$slug'
      path: '/artwork/$slug'
      fullPath: '/artwork/$slug'
      preLoaderRoute: typeof ArtworkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artworks': {
      id: '/api/artworks'
      path: '/api/artworks'
      fullPath: '/api/artworks'
      preLoaderRoute: typeof ApiArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/series': {
      id: '/admin/series'
      path: '/series'
      fullPath: '/admin/series'
      preLoaderRoute: typeof AdminSeriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artworks': {
      id: '/admin/artworks'
      path: '/artworks'
      fullPath: '/admin/artworks'
      preLoaderRoute: typeof AdminArtworksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/series': {
      id: '/api/admin/series'
      path: '/api/admin/series'
      fullPath: '/api/admin/series'
      preLoaderRoute: typeof ApiAdminSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/inquiries': {
      id: '/api/admin/inquiries'
      path: '/api/admin/inquiries'
      fullPath: '/api/admin/inquiries'
      preLoaderRoute: typeof ApiAdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/artworks': {
      id: '/api/admin/artworks'
      path: '/api/admin/artworks'
      fullPath: '/api/admin/artworks'
      preLoaderRoute: typeof ApiAdminArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artworks/new': {
      id: '/admin/artworks/new'
      path: '/new'
      fullPath: '/admin/artworks/new'
      preLoaderRoute: typeof AdminArtworksNewRouteImport
      parentRoute: typeof AdminArtworksRoute
    }
    '/admin/artworks/$artworkId': {
      id: '/admin/artworks/$artworkId'
      path: '/$artworkId'
      fullPath: '/admin/artworks/$artworkId'
      preLoaderRoute: typeof AdminArtworksArtworkIdRouteImport
      parentRoute: typeof AdminArtworksRoute
    }
    '/api/admin/artworks/reorder': {
      id: '/api/admin/artworks/reorder'
      path: '/reorder'
      fullPath: '/api/admin/artworks/reorder'
      preLoaderRoute: typeof ApiAdminArtworksReorderRouteImport
      parentRoute: typeof ApiAdminArtworksRoute
    }
    '/api/admin/artworks/$artworkId': {
      id: '/api/admin/artworks/$artworkId'
      path: '/$artworkId'
      fullPath: '/api/admin/artworks/$artworkId'
      preLoaderRoute: typeof ApiAdminArtworksArtworkIdRouteImport
      parentRoute: typeof ApiAdminArtworksRoute
    }
  }
}

interface AdminArtworksRouteChildren {
  AdminArtworksArtworkIdRoute: typeof AdminArtworksArtworkIdRoute
  AdminArtworksNewRoute: typeof AdminArtworksNewRoute
}

const AdminArtworksRouteChildren: AdminArtworksRouteChildren = {
  AdminArtworksArtworkIdRoute: AdminArtworksArtworkIdRoute,
  AdminArtworksNewRoute: AdminArtworksNewRoute,
}

const AdminArtworksRouteWithChildren = AdminArtworksRoute._addFileChildren(
  AdminArtworksRouteChildren,
)

interface AdminRouteChildren {
  AdminArtworksRoute: typeof AdminArtworksRouteWithChildren
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSeriesRoute: typeof AdminSeriesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtworksRoute: AdminArtworksRouteWithChildren,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSeriesRoute: AdminSeriesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminArtworksRouteChildren {
  ApiAdminArtworksArtworkIdRoute: typeof ApiAdminArtworksArtworkIdRoute
  ApiAdminArtworksReorderRoute: typeof ApiAdminArtworksReorderRoute
}

const ApiAdminArtworksRouteChildren: ApiAdminArtworksRouteChildren = {
  ApiAdminArtworksArtworkIdRoute: ApiAdminArtworksArtworkIdRoute,
  ApiAdminArtworksReorderRoute: ApiAdminArtworksReorderRoute,
}

const ApiAdminArtworksRouteWithChildren =
  ApiAdminArtworksRoute._addFileChildren(ApiAdminArtworksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiArtworksRoute: ApiArtworksRoute,
  ApiContactRoute: ApiContactRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  ApiUploadRoute: ApiUploadRoute,
  ArtworkSlugRoute: ArtworkSlugRoute,
  ApiAdminArtworksRoute: ApiAdminArtworksRouteWithChildren,
  ApiAdminInquiriesRoute: ApiAdminInquiriesRoute,
  ApiAdminSeriesRoute: ApiAdminSeriesRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
